# https://deepsource.io/docs/config/deepsource-toml.html
# https://deepsource.io/docs/analyzer/python.html

version = 1

test_patterns = [
  "tests/*.py",
  "tests/**/*.py"
]

exclude_patterns = [
  "setup.py",
  "samples/**",
  "tests/**",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 125

